#!/usr/bin/env python3
"""
Import localized item names from Raidbots item-names.json into hotfixes locale tables.

Source: https://www.raidbots.com/static/data/live/item-names.json (build 66192)
Targets:
  - hotfixes.item_sparse_locale   (Display_lang column)
  - hotfixes.item_search_name_locale (Display_lang column)

Uses INSERT ... ON DUPLICATE KEY UPDATE to be idempotent.
Generates SQL files, does not execute directly.
"""

import json
import os
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
INPUT_FILE = SCRIPT_DIR / "item-names.json"
OUTPUT_DIR = SCRIPT_DIR / "sql_output"
VERIFIED_BUILD = 66192

# Raidbots locale -> TrinityCore locale code mapping (skip en_US, it's the base)
LOCALE_MAP = {
    "de_DE": "deDE",
    "es_ES": "esES",
    "es_MX": "esMX",
    "fr_FR": "frFR",
    "it_IT": "itIT",
    "ko_KR": "koKR",
    "pt_BR": "ptBR",
    "ru_RU": "ruRU",
    "zh_CN": "zhCN",
    "zh_TW": "zhTW",
}

BATCH_SIZE = 500


def escape_sql(s: str) -> str:
    """Escape a string for MySQL single-quoted literal."""
    if s is None:
        return "NULL"
    return s.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n").replace("\r", "\\r").replace("\x00", "\\0").replace("\x1a", "\\Z")


def write_sql_header(f, table: str):
    """Write SQL file header with USE, SET, and transaction preamble."""
    f.write(f"-- Localized item names for {table}\n")
    f.write(f"-- Source: Raidbots item-names.json (build {VERIFIED_BUILD})\n")
    f.write(f"-- Generated by import_item_names.py\n\n")
    f.write("USE hotfixes;\n\n")
    f.write("SET NAMES utf8mb4;\n")
    f.write("SET autocommit = 0;\n")
    f.write("SET UNIQUE_CHECKS = 0;\n")
    f.write("SET FOREIGN_KEY_CHECKS = 0;\n")
    f.write("START TRANSACTION;\n\n")


def write_sql_footer(f):
    """Write SQL file footer with COMMIT and restore settings."""
    f.write("COMMIT;\n")
    f.write("SET UNIQUE_CHECKS = 1;\n")
    f.write("SET FOREIGN_KEY_CHECKS = 1;\n")
    f.write("SET autocommit = 1;\n")


def generate_sql(item_names: dict, valid_ids: set | None, table: str, filename: str):
    """Generate SQL file for one locale table."""
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    outpath = OUTPUT_DIR / filename

    total_rows = 0
    locale_counts = {}

    with open(outpath, "w", encoding="utf-8") as f:
        write_sql_header(f, table)

        for rb_locale, tc_locale in LOCALE_MAP.items():
            # Collect all rows for this locale first
            all_rows = []
            for item_id_str, locales in item_names.items():
                item_id = int(item_id_str)

                # If we have a valid_ids set, skip items not in the target table
                if valid_ids is not None and item_id not in valid_ids:
                    continue

                name = locales.get(rb_locale)
                if not name:
                    continue

                # Skip if identical to English (no point storing a duplicate)
                en_name = locales.get("en_US", "")
                if name == en_name:
                    continue

                all_rows.append((item_id, tc_locale, name))

            locale_count = len(all_rows)
            locale_counts[rb_locale] = locale_count
            total_rows += locale_count

            f.write(f"-- Locale: {rb_locale} ({tc_locale})\n")

            if locale_count == 0:
                # No replacement data — leave existing rows (e.g. stub locales) untouched
                f.write(f"-- SKIPPED: no data in source for this locale, preserving existing rows\n\n")
                print(f"  WARNING: {rb_locale} ({tc_locale}): 0 items — locale not present in source data")
                continue

            # Only delete old-build rows when we have replacement data
            f.write(f"DELETE FROM `{table}` WHERE `locale` = '{tc_locale}' AND `VerifiedBuild` != {VERIFIED_BUILD};\n\n")

            # Write batches
            for i in range(0, locale_count, BATCH_SIZE):
                write_batch(f, table, all_rows[i:i + BATCH_SIZE])

            print(f"  {rb_locale} ({tc_locale}): {locale_count:,} items")

        write_sql_footer(f)

    # Final summary for this file
    print(f"  ---")
    print(f"  {filename}: {total_rows:,} total rows written to {outpath}")
    return total_rows


def write_batch(f, table: str, batch: list):
    """Write one INSERT ... ON DUPLICATE KEY UPDATE batch."""
    f.write(f"INSERT INTO `{table}` (`ID`, `locale`, `Display_lang`, `VerifiedBuild`) VALUES\n")
    lines = []
    for item_id, locale, name in batch:
        lines.append(f"({item_id}, '{locale}', '{escape_sql(name)}', {VERIFIED_BUILD})")
    f.write(",\n".join(lines))
    f.write(f"\nAS new ON DUPLICATE KEY UPDATE `Display_lang` = new.`Display_lang`, `VerifiedBuild` = new.`VerifiedBuild`;\n\n")


def main():
    print(f"Loading {INPUT_FILE}...")
    with open(INPUT_FILE, encoding="utf-8") as f:
        data = json.load(f)

    item_names = data.get("ItemSparse", {})
    print(f"  {len(item_names):,} items with localized names")

    # Load valid IDs from the DB export, or skip filtering if not available
    # We'll generate both tables and let MySQL handle mismatches via INSERT IGNORE-style

    all_ids = set(int(k) for k in item_names.keys())
    print(f"  ID range: {min(all_ids)} - {max(all_ids)}")

    # Load valid item_search_name IDs so we only insert matching rows
    search_name_ids_file = SCRIPT_DIR / "item_search_name_ids.txt"
    search_name_ids = None
    if search_name_ids_file.exists():
        search_name_ids = set()
        with open(search_name_ids_file) as f:
            for line in f:
                line = line.strip()
                if line.isdigit():
                    search_name_ids.add(int(line))
        print(f"  Loaded {len(search_name_ids):,} valid item_search_name IDs for filtering")

    # Generate for item_sparse_locale (all items — item_sparse has 171K rows, close match)
    print("\nGenerating item_sparse_locale SQL...")
    n1 = generate_sql(item_names, None, "item_sparse_locale", "item_sparse_locale.sql")

    # Generate for item_search_name_locale (filtered to valid IDs only)
    print("\nGenerating item_search_name_locale SQL...")
    n2 = generate_sql(item_names, search_name_ids, "item_search_name_locale", "item_search_name_locale.sql")

    # Grand total summary
    print(f"\n{'='*50}")
    print(f"Grand total: {n1 + n2:,} rows across 2 files")
    print(f"  item_sparse_locale.sql:       {n1:,} rows")
    print(f"  item_search_name_locale.sql:  {n2:,} rows")
    print(f"Output: {OUTPUT_DIR}/")
    print(f"\nTo import:")
    print(f'  mysql -u root -padmin < "{OUTPUT_DIR}/item_sparse_locale.sql"')
    print(f'  mysql -u root -padmin < "{OUTPUT_DIR}/item_search_name_locale.sql"')


if __name__ == "__main__":
    main()
